import { Product } from './model/types'

export const PRODUCTS: Product[] = [
	{
		id: 1,
		slug: 'dorama-box',
		name: 'TARIMI Dorama Box',
		img: '/images/ramens/dorama/1.png',
		category: 'sets',
		price: 1290,
		desc: 'Полный набор для уютного азиатского вечера дома: 6 порций рамена, соус, нори, сладости и палочки. Наслаждайтесь атмосферой Кореи и других стран Азии 🏮',
		hot: true,

		// salePercent: 17,
		dateAdded: '2025-10-29',
	},
	{
		id: 2,
		slug: 'dorama-box-mini-1',
		name: 'TARIMI Dorama miniBox (1 вар.)',
		img: '/images/ramens/dorama-mini-1/dorama-mini-1-1.png',
		category: 'sets',
		price: 790,
		desc: 'Мини-набор с 3 вкусами рамена, сладостями, палочками и допами. Лёгкий способ устроить атмосферный вечер с азиатской едой дома 💞',
		limited: true,
		// salePercent: 17,
		dateAdded: '2025-10-29',
	},
	{
		id: 3,
		slug: 'dorama-box-mini-2',
		name: 'TARIMI Dorama miniBox (2 вар.)',
		img: '/images/ramens/dorama-mini-2/dorama-mini-2-1.png',
		category: 'sets',
		price: 790,
		desc: 'Мини-набор для азиатского вечера: рамен, сладости, палочки и допы. Погрузитесь в атмосферу K-дорам и street food из Азии 🏮',
		limited: true,
		// salePercent: 17,
		dateAdded: '2025-10-29',
	},
	{
		id: 4,
		slug: 'spicy-box',
		name: 'TARIMI Spicy Box',
		img: '/images/ramens/spicy/spicy-full-1.png',
		category: 'sets',
		price: 1290,
		desc: 'Острый азиатский набор: 6 порций рамена с разной степенью остроты, сладости, соус, нори и палочки 🌶️ Идеально для любителей драйва и новых вкусов',
		new: true,
		dateAdded: '2025-12-29',
	},
	{
		id: 5,
		slug: 'spicy-box-mini',
		name: 'TARIMI Spicy miniBox',
		img: '/images/ramens/spicy-mini/spicy-mini-1.png',
		category: 'sets',
		price: 790,
		desc: 'Мини-набор с острым раменом, сладостями и допами 🌶️ Быстрый способ устроить острый вечер с азиатской едой дома',
		new: true,
		limited: true,
		dateAdded: '2025-12-29',
	},
]
