import { Product } from './model/types';

export const PRODUCTS: Product[] = [
  {
    id: 1,
    slug: 'dorama-box',
    name: 'TARIMI Dorama Box',
    img: '/images/ramens/dorama/1.png',
    category: 'sets',
    price: 1290,
    desc: 'Полный набор для уютного азиатского вечера дома: 6 порций рамена, соус, нори, сладости и палочки. Наслаждайтесь атмосферой Кореи и других стран Азии 🏮',
    hot: false,
    outOfStock: true,
    dateAdded: '2025-10-29',
  },
  {
    id: 2,
    slug: 'dorama-box-mini-1',
    name: 'TARIMI Dorama miniBox (1 вар.)',
    img: '/images/ramens/dorama-mini-1/dorama-mini-1-1.png',
    category: 'sets',
    price: 990,
    desc: 'Мини-набор с 3 вкусами рамена, сладостями, палочками и допами. Лёгкий способ устроить атмосферный вечер с азиатской едой дома 💞',
    hot: true,
    dateAdded: '2025-10-29',
  },
  {
    id: 3,
    slug: 'dorama-box-mini-2',
    name: 'TARIMI Dorama miniBox (2 вар.)',
    img: '/images/ramens/dorama-mini-2/dorama-mini-2-1.png',
    category: 'sets',
    price: 990,
    desc: 'Мини-набор для азиатского вечера: рамен, сладости, палочки и допы. Погрузитесь в атмосферу K-дорам и street food из Азии 🏮',
    // hot: true,
    dateAdded: '2025-10-29',
  },
  {
    id: 4,
    slug: 'spicy-box',
    name: 'TARIMI Spicy Box',
    img: '/images/ramens/spicy/spicy-full-1.png',
    category: 'sets',
    price: 1290,
    desc: 'Острый азиатский набор: 6 порций рамена с разной степенью остроты, сладости, соус, нори и палочки 🌶️ Идеально для любителей драйва и новых вкусов',
    new: false,
    outOfStock: true,
    dateAdded: '2025-12-29',
  },
  {
    id: 5,
    slug: 'spicy-box-mini',
    name: 'TARIMI Spicy miniBox',
    img: '/images/ramens/spicy-mini/spicy-mini-1.png',
    category: 'sets',
    price: 990,
    desc: 'Мини-набор с острым раменом, сладостями и допами 🌶️ Быстрый способ устроить острый вечер с азиатской едой дома',
    new: false,

    dateAdded: '2025-12-29',
  },
  {
    id: 6,
    slug: 'cheese-box',
    name: 'TARIMI Cheese Box',
    img: '/images/ramens/cheese/1.png',
    category: 'sets',
    price: 990,
    desc: 'Сливочный азиатский набор: нежный рамен с сырным вкусом, сладости, соус, нори и палочки 🧀 Для любителей мягких и молочных ноток в корейской кухне',
    dateAdded: '2026-04-19',
    new: true,
  },
  {
    id: 7,
    slug: 'carbonara-box',
    name: 'TARIMI Carbonara Box',
    img: '/images/ramens/carbonara/1.png',
    category: 'sets',
    price: 990,
    desc: 'Итальянско-корейский фьюжн: рамен карбонара в азиатском стиле, сладости, соус, нори и палочки 🍝 Уникальное сочетание сыра, бекона и корейского характера',
    dateAdded: '2026-04-19',
    new: true,
  },
  {
    id: 8,
    slug: 'origin-box',
    name: 'TARIMI Origin Box',
    img: '/images/ramens/origin/1.png',
    category: 'sets',
    price: 990,
    desc: 'Классический азиатский набор: традиционный рамен, сладости, нори и палочки. Чистый вкус Кореи без лишних добавок 🇰🇷',
    dateAdded: '2026-04-19',
    new: true,
  },
  {
    id: 9,
    slug: 'nong-classic-box',
    name: 'TARIMI Nong-Classic Box',
    img: '/images/ramens/nong-classicbox/1.png',
    category: 'sets',
    price: 990,
    desc: 'Премиум набор с раменом Nongshim: классические вкусы, сладости, соус, нори и палочки 🍜 Легендарный рамен с богатой историей',
    dateAdded: '2026-04-19',
    new: true,
  },
  {
    id: 10,
    slug: 'nong-tom-yum-box',
    name: 'TARIMI Nong Tom Yum (creamy) Box',
    img: '/images/ramens/nong-tom-yum/1.png',
    category: 'sets',
    price: 990,
    desc: 'Тайско-корейский набор: сливочный том-ям рамен Nongshim, сладости, соус, нори и палочки, специи и морепродукты для настоящего взрыва вкуса',
    dateAdded: '2026-04-19',
    new: true,
  },
];
