import type { Metadata } from 'next'
import { Nabla, Inter, Red_Rose } from 'next/font/google'
import '../../styles/base.scss'
import StoreProvider from '../providers/StoreProvider'
import { QueryProvider } from '../providers/QueryProvider'
import Header from '@/widgets/header/ui/Header/Header'
import { IHeaderModes } from '@/widgets/header/model/types'
import StyledComponentsRegistry from '@/shared/ui/StyledComponentsRegistry/StyledComponentsRegistry.tsx'

const nabla = Nabla({
	variable: '--font-nabla',
	subsets: ['latin'],
})
const red_rose = Red_Rose({
	variable: '--font-red-rose',
	subsets: ['latin'],
})

const inter = Inter({
	variable: '--font-inter',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Main',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang='ru'>
			<body
				className={`${nabla.variable} ${red_rose.variable} ${inter.variable} antialiased`}
			>
				<StyledComponentsRegistry>
					<StoreProvider>
						<QueryProvider>
							<Header mode={IHeaderModes.private} />
							{children}
						</QueryProvider>
					</StoreProvider>
				</StyledComponentsRegistry>
			</body>
		</html>
	)
}
